name: CI

on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * *"

jobs:
  gnu:
    name: Process the GNU test results
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install jq python3-pandas python3-matplotlib

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download the result
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: compat.yml
        name: gnu-result
        repo: uutils/findutils
        path: dl

    - name: Merge the json files
      shell: bash
      run: |
       echo "== dl/gnu-result.json =="
       cat dl/gnu-result.json
       echo "== gnu-result.json =="
       cat gnu-result.json
       jq -s '.[0] * .[1]' gnu-result.json dl/gnu-result.json > merged.json
       echo "== merged.json ="
       cat merged.json
       mv merged.json gnu-result.json
       rm -rf dl

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: "Update of the GNU data"
        pull: '--autostash'

    - name: Generate the graph
      shell: bash
      run: |
        python graph.py gnu-result.json

    - name: Add & Commit the graph
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: "Refresh the graph"
        add: gnu-results.png

  bfs:
    name: Process the BFS test results
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install jq python3-pandas python3-matplotlib

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download the result
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: compat.yml
        name: bfs-result
        repo: uutils/findutils
        path: dl

    - name: Merge the json files
      shell: bash
      run: |
       echo "== dl/bfs-result.json =="
       cat dl/bfs-result.json
       echo "== bfs-result.json =="
       cat bfs-result.json
       jq -s '.[0] * .[1]' bfs-result.json dl/bfs-result.json > merged.json
       echo "== merged.json ="
       cat merged.json
       mv merged.json bfs-result.json
       rm -rf dl

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: "Update of the BFS data"
        pull: '--autostash'

    - name: Generate the graph
      shell: bash
      run: |
        python graph.py bfs-result.json

    - name: Add & Commit the graph
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: "Refresh the graph"
        add: bfs-results.png
